### PR TITLE
Fix/193 sub menu hover

### LINKED ISSUE #193: Menus with sub-sub menus on hover
@markconroy 
I think we still need to do some work on the menu on hover. 

If we have a menu item with multiple children and some grandchildren eg

Screenshot from 2022-12-08 10-54-48

then when we hover over the first child we can hover to its child, but the menu disappears before we can hover over the second child. 

Hard to describe, let's discuss.

### PR DESCRIPTION
**Pull request by markconroy**
Closes #193 

## What does this change?

Removes hover functionality, so you must explicitely click the toggle button to activate sub menus.

## How to test
Create a microsite with nested sub menus, check that you can access all sub menu items.

### CODE REVIEW

**Comment by finnlewis** [comment]
I'm testing this and can't even get a sub menu to display. Only the top level menu links.
What am I missing?

**Comment by markconroy** [comment]
@finnlewis you probably need to set the menu item's "Show as expanded" checkbox on the parent menu items.

**Comment by msayoung** [comment]
@finnlewis mark is right, you have to check "show as expanded" in the display settings tab on the parent menu item. Irritating

@markconroy this does fix the situation with the submenus - 

however now when you remove hover from the top level button the dropdown closes. As you have to click to open it I'd expect you'd also need to click to close. Thoughts ?

**Comment by markconroy** [comment]
@msayoung can you give this a test again please?

**Comment by finnlewis** [comment]
I'm testing this now.

**Comment by finnlewis** [comment]
Works a treat! 

Confirmed that on the default branch, hover activates the drop down. 

On this branch, the drop down is only activate on click (or space / enter keys).

To close it also now requires another click..

Very cool!

**Review by finnlewis — APPROVED** [review]

**Pull request merged**
