### PR TITLE
updates package.json

### LINKED ISSUE #125: Ensure theme creation script has correct templates, update README to show how to use this

### PR DESCRIPTION
**Pull request by markconroy**
Closes #125 

## What does this change?

Updates package.json so the CSS linter can run in custom sub themes.

### CODE REVIEW

**Comment by finnlewis** [comment]
Hey @markconroy 

Just trying to test this. 

Sorry, I'm probably being a bit dense, but how do we run the css linter? 

Cheers,

Finn

**Comment by finnlewis** [comment]
I've tried an `npm install`, then

```
finn@localgov-microsites-web:/var/www/html/web/themes/contrib/localgov_microsites_base$ npm run start

> localgov_subtheme@1.0.0 start
> npm run lint:css


> localgov_subtheme@1.0.0 lint:css
> stylelint "**/*.css" --fix

Error: Could not find "stylelint-prettier/recommended". Do you need the "configBasedir" or "--config-basedir" option?
    at configurationError (/var/www/html/web/themes/contrib/localgov_microsites_base/node_modules/stylelint/lib/utils/configurationError.js:12:49)
    at getModulePath (/var/www/html/web/themes/contrib/localgov_microsites_base/node_modules/stylelint/lib/utils/getModulePath.js:28:9)
    at loadExtendedConfig (/var/www/html/web/themes/contrib/localgov_microsites_base/node_modules/stylelint/lib/augmentConfig.js:216:21)
    at extendConfig (/var/www/html/web/themes/contrib/localgov_microsites_base/node_modules/stylelint/lib/augmentConfig.js:184:25)
    at async augmentConfigBasic (/var/www/html/web/themes/contrib/localgov_microsites_base/node_modules/stylelint/lib/augmentConfig.js:57:20)
    at async extendConfig (/var/www/html/web/themes/contrib/localgov_microsites_base/node_modules/stylelint/lib/augmentConfig.js:193:25)
    at async augmentConfigBasic (/var/www/html/web/themes/contrib/localgov_microsites_base/node_modules/stylelint/lib/augmentConfig.js:57:20)
    at async augmentConfigFull (/var/www/html/web/themes/contrib/localgov_microsites_base/node_modules/stylelint/lib/augmentConfig.js:111:24)
    at async search (/var/www/html/web/themes/contrib/localgov_microsites_base/node_modules/cosmiconfig/dist/Explorer.js:47:36)
    at async search (/var/www/html/web/themes/contrib/localgov_microsites_base/node_modules/cosmiconfig/dist/Explorer.js:64:28)
finn@localgov-microsites-web:/var/www/html/web/themes/contrib/localgov_microsites_base$ npm run lint:css

> localgov_subtheme@1.0.0 lint:css
> stylelint "**/*.css" --fix

Error: Could not find "stylelint-prettier/recommended". Do you need the "configBasedir" or "--config-basedir" option?
    at configurationError (/var/www/html/web/themes/contrib/localgov_microsites_base/node_modules/stylelint/lib/utils/configurationError.js:12:49)
    at getModulePath (/var/www/html/web/themes/contrib/localgov_microsites_base/node_modules/stylelint/lib/utils/getModulePath.js:28:9)
    at loadExtendedConfig (/var/www/html/web/themes/contrib/localgov_microsites_base/node_modules/stylelint/lib/augmentConfig.js:216:21)
    at extendConfig (/var/www/html/web/themes/contrib/localgov_microsites_base/node_modules/stylelint/lib/augmentConfig.js:184:25)
    at async augmentConfigBasic (/var/www/html/web/themes/contrib/localgov_microsites_base/node_modules/stylelint/lib/augmentConfig.js:57:20)
    at async extendConfig (/var/www/html/web/themes/contrib/localgov_microsites_base/node_modules/stylelint/lib/augmentConfig.js:193:25)
    at async augmentConfigBasic (/var/www/html/web/themes/contrib/localgov_microsites_base/node_modules/stylelint/lib/augmentConfig.js:57:20)
    at async augmentConfigFull (/var/www/html/web/themes/contrib/localgov_microsites_base/node_modules/stylelint/lib/augmentConfig.js:111:24)
    at async search (/var/www/html/web/themes/contrib/localgov_microsites_base/node_modules/cosmiconfig/dist/Explorer.js:47:36)
    at async search (/var/www/html/web/themes/contrib/localgov_microsites_base/node_modules/cosmiconfig/dist/Explorer.js:64:28) 

```

**Comment by finnlewis** [comment]
@stephen-cox pointed out there is some notes on linting here https://github.com/localgovdrupal/localgov_base?tab=readme-ov-file#automated-css-coding-standards

**Comment by markconroy** [comment]
You are probably missing the core set up that this leverages from. You might need to run these commands first:

```
cd web/core
npm install
```
That will get all the core linting stuff, then you can run our commands which uses the same stylelint file as core does.

**Comment by finnlewis** [comment]
Thanks @markconroy, I'll give that a go and update the README if that's the way.

**Comment by millnut** [comment]
As it's slightly related @finnlewis I have some work to finish here https://github.com/localgovdrupal/localgov_shared_workflows/pull/11 which will add ESLint and Stylelint checks to workflows.

However it does report a lot of errors across everything when checking using Drupal's JS/CSS standards, I was planning to make it opt-in first (hopefully wrap that up end of this week) so everything doesn't start failing.

**Comment by markconroy** [comment]
@millnut The CSS standards should be fairly OK now. I ran the linter on all the themes. Modules providing custom CSS could be a different story.

JS will definitely be a bit whack, but maybe we can get them all linted next week or the week after. Once they are done once and the system is enforced it easy to keep it in place.

**Comment by millnut** [comment]
@markconroy good point, I'll fix the conflicts and look at submitting it for review again

**Pull request merged**
