### PR TITLE
Move getActiveDomainGroup to service with getActiveDomainGroupId().

### PR DESCRIPTION
**Pull request by ekes**
In adding to context ended up making this a service and clarifying method names.

### CODE REVIEW

**Review by stephen-cox — APPROVED** [review]
Looks good to me

**Comment by markconroy** [comment]
I'm getting an error
```Error: Call to undefined method Drupal\domain_group\DomainGroupResolver::getActiveDomainGroupId() in localgov_microsites_base_preprocess_html() (line 15 of themes/contrib/localgov_microsites_base/localgov_microsites_base.theme). ```

Is there another PR that needs to be merged before this one?

**Comment by stephen-cox** [comment]
> I'm getting an error `Error: Call to undefined method Drupal\domain_group\DomainGroupResolver::getActiveDomainGroupId() in localgov_microsites_base_preprocess_html() (line 15 of themes/contrib/localgov_microsites_base/localgov_microsites_base.theme). `
> 
> Is there another PR that needs to be merged before this one?

You'll need to make sure you have the latest changes to the Domain Group module. I did a `composer update` before checking out this branch and testing it

**Comment by markconroy** [comment]
Works a treat.

**Pull request merged**
