### PR TITLE
Font: Adobe Source sans v3

### PR DESCRIPTION
**Pull request by Adnan-cds**
Requesting addition of the [Adobe Source sans font](https://github.com/adobe-fonts/source-sans/) at the suggestion of @clearspotmedia

### CODE REVIEW

**Comment by msayoung** [comment]
@Adnan-cds - I think you'll need to update the config on localgov_microsites_group to allow this to be chosen through the UI. Is that the intention. 

Also, I don't mind, but I don't know what the process is follow allowing more fonts ! :)

**Comment by markconroy** [comment]
It's a very well supported and fleshed-out font. I wouldn't have a problem adding this one to our offering.

**Comment by clearspotmedia** [comment]
It's a commonly used font, a good accessible option for Councils. Croydon uses Source Sans as the main body font so the font being available in mico sites options is needed to be 'on brand'.

**Comment by Adnan-cds** [comment]
> you'll need to update the config on localgov_microsites_group to allow this to be chosen through the UI. Is that the intention.

That's right Maria.  If this change is accepted, I will have to raise a follow up one for the [localgov_microsites_group](https://github.com/localgovdrupal/localgov_microsites_group/) module where we need to update the following config files and also add an update hook implementation to apply it to existing sites:
- [Body font selection field](https://github.com/localgovdrupal/localgov_microsites_group/blob/2.x/config/install/field.storage.group.lgms_body_font.yml).
- [Header font selection field](https://github.com/localgovdrupal/localgov_microsites_group/blob/2.x/config/install/field.field.group.microsite.lgms_heading_font.yml).
- [H1 font selection field](https://github.com/localgovdrupal/localgov_microsites_group/blob/2.x/config/install/field.storage.group.lgms_heading_1_font.yml).
- [H2 font selection field](https://github.com/localgovdrupal/localgov_microsites_group/blob/2.x/config/install/field.storage.group.lgms_heading_2_font.yml).
- [H3 font selection field](https://github.com/localgovdrupal/localgov_microsites_group/blob/2.x/config/install/field.storage.group.lgms_heading_3_font.yml).
- [H4 font selection field](https://github.com/localgovdrupal/localgov_microsites_group/blob/2.x/config/install/field.storage.group.lgms_heading_4_font.yml).
- [H5 font selection field](https://github.com/localgovdrupal/localgov_microsites_group/blob/2.x/config/install/field.storage.group.lgms_heading_5_font.yml).
- [H6 font selection field](https://github.com/localgovdrupal/localgov_microsites_group/blob/2.x/config/install/field.storage.group.lgms_heading_6_font.yml).

**Comment by finnlewis** [comment]
It's a great font, +1 from me. 

Can we get this in @markconroy @msayoung ?

**Comment by msayoung** [comment]
fine by me

**Review by msayoung — APPROVED** [review]

**Review by markconroy — APPROVED** [review]

**Pull request merged**
