### PR TITLE
setting image style for events listing images

### LINKED ISSUE #62: Set image style for items in events listings
Events list does not use view modes, so we need a hook_views_alter type approach to set the image style for the events image view in the /events listing

### LINKED ISSUE #92: Allow items in a section to have the same height

### PR DESCRIPTION
**Pull request by markconroy**
Closes #62

### CODE REVIEW

**Comment by markconroy** [comment]
@stephen-cox @ekes Going to assign this to you (at least temporarily) while I declare bankruptcy on it.

This is the current problematic line https://github.com/localgovdrupal/localgov_microsites_base/pull/94/files#diff-ccbd935b8318ed849c451f7bb151bdb038fd4df8dd300e228538a8545b2bd630R539

**Comment by stephen-cox** [comment]
@markconroy I have updated the code, but it's still not working. This is a little tricker than it looks.

We need to change the display options on the view not the field config. I've tried this, but it's not working properly. 

```php
      $image_field = $view->field['localgov_event_image'];
      $image_field->options['settings']['view_mode'] = $image_style;
```

Will need to take another look at it

**Comment by stephen-cox** [comment]
@markconroy This should be working now

**Comment by msayoung** [comment]
Beautiful

**Review by msayoung — APPROVED** [review]

**Comment by finnlewis** [comment]
@markconroy you good to merge this?

**Comment by markconroy** [comment]
Looks good to me, let's merge. Thanks @stephen-cox

**Pull request merged**
