### PR TITLE
initial commit for hiding breadcrumbs on homepage

### LINKED ISSUE #207: Removing bread crumbs from the home page
I am wanting to remove the breadcrumbs from the home page as there is no path yet created thus leaving 'Home' as the only breadcrumb.

It has been recommended that this is created as a check box.

### PR DESCRIPTION
**Pull request by markconroy**
Closes #207

### CODE REVIEW

**Comment by markconroy** [comment]
@ekes and/or @stephen-cox would one of you look at the `@todo` in this PR. I think you'll be quicker than me at unsetting the breadcrumbs block if that checkbox is checked in the group site settings.

**Comment by finnlewis** [comment]
@markconroy I had a little play to see how this might work. 

I didn't get it working in the hook_preprocess_page() but did with hook_preprocess_breadcrumb().

The thing is, this duplicates a bunch of logic we already have in hook_preprocess_page().

Like this: 

```
function localgov_microsites_base_preprocess_breadcrumb(&$variables) {
  $parent_group_id = \Drupal::service('domain_group_resolver')->getActiveDomainGroupId();
  if ($parent_group_id) {
    $group = \Drupal::entityTypeManager()->getStorage('group')->load($parent_group_id);
  }
  if (empty($group)) {
    $group = \Drupal::request()->attributes->get('group');
  }
  if ($group instanceof MicrositeGroupInterface) {
    $front_page = \Drupal::config('domain.config.group_' . $parent_group_id . '.system.site')->get('page.front');
    $current_path = \Drupal::service('path.current')->getPath();
    $current_path_alias = \Drupal::service('path_alias.manager')->getAliasByPath($current_path);
    if (($front_page === $current_path || $front_page === $current_path_alias)) {
      if (isset($group->get('lgms_hide_home_breadcrumbs')[0])) {
        if ($group->get('lgms_hide_home_breadcrumbs')[0]->getValue()['value'] === "1") {
          unset($variables['breadcrumb']);
        }
      }
    }
  }
}
```
@ekes @stephen-cox - is there a cleaner way?

**Comment by markconroy** [comment]
@finnlewis I was trying to do something similar in hook_preprocess_page to do something like 

`unset($variables['page']['breadcrumb']` and other variations of that, but unsuccessfully.

**Comment by finnlewis** [comment]
note - you will need to use the branch from 
https://github.com/localgovdrupal/localgov_microsites_group/pull/389 

https://github.com/localgovdrupal/localgov_microsites_group/tree/feature/2.x/hide-breadcrumbs-home-page/388

**Comment by ekes** [comment]
I think the way to do this is not to show the breadcrumb block, so configure it to exclude display on `<front>` which will work on all the microsites.

To make it then configurable per multisite will require a config override on the block config per domain. A technical admin could do this with the domain_config by creating an override yml. For a site admin to do so with the info from a field I guess it's best for us to implement the config override service ourselves.

**Comment by markconroy** [comment]
@ekes I'm happy for us to your your approach, or my approach. I don't have a preference for either - like you said in Slack, it's probably an edge case to _want_ breadcrumbs on the homepage.

**Comment by willguv** [comment]
@ekes I'm wondering if we can save you some work. I can't remember the last time I've seen breadcrumbs on a homepage so maybe they can just be removed?

Does this make the issue go away?

**Comment by ekes** [comment]
So it went with this https://github.com/localgovdrupal/localgov_microsites_base/pull/214

**Pull request closed without merging**
