### PR TITLE
Remove template which is now in localgov_base

### PR DESCRIPTION
**Pull request by msayoung**

### CODE REVIEW

**Comment by finnlewis** [comment]
Looks like we'll want https://github.com/localgovdrupal/localgov_base/pull/240/files merged and released before merging this one.

**Comment by markconroy** [comment]
@msayoung can you check what merge conflict we have here?

**Comment by markconroy** [comment]
@msayoung  This looks like we are addding the template back in

**Comment by msayoung** [comment]
@markconroy - it should be fine now. We're removing the template here because it is now in localgov_base

**Pull request merged**
