### PR TITLE
Update teaser template to print the directory image for Directory Pro…

### PR DESCRIPTION
**Pull request by msayoung**
…mo Pages

### CODE REVIEW

**Comment by msayoung** [comment]
@markconroy not completely sure about the display of the image, but it is following the pattern we have elsewhere

**Comment by markconroy** [comment]
Looks like you are missing the section from the `.theme` file that sets the teaser image style.

**Comment by markconroy** [comment]
Hi @msayoung 

I think this is ready for your eagle eye again, thanks!

**Comment by msayoung** [comment]
Hey @markconroy - great, thanks! 
I can't approve this as it was mine to start with :)

**Pull request merged**
