### PR TITLE
Add some unpublished styling

### PR DESCRIPTION
**Pull request by msayoung**

### CODE REVIEW

**Comment by finnlewis** [comment]
@msayoung wants to change this a bit

**Comment by finnlewis** [comment]
Hey @msayoung - still want to change this a bit?

**Comment by finnlewis** [comment]
Leaving this for @msayoung to review.

**Comment by markconroy** [comment]
@msayoung let's fix this for LGD rather than just microsites. See issue https://github.com/localgovdrupal/localgov_base/issues/464

**Comment by markconroy** [comment]
Closing this. I think it's completed via https://github.com/localgovdrupal/localgov_base/pull/476

If we want to further improve it, let's do it at the `localgov_base` level if possible.

**Pull request closed without merging**
