### PR TITLE
removes quote around font-weight property, so they apply correctly

### LINKED ISSUE #45: Heading font weight bold not applying
Tested with Open Sans (in the Golbal Styles)

### PR DESCRIPTION
**Pull request by markconroy**
Fixes #45

### CODE REVIEW

**Comment by msayoung** [comment]
@markconroy Bold and Normal are working, but not semi-bold. Perhaps because we need the 600 weight font files

**Review by msayoung — CHANGES_REQUESTED** [review]
bold and normal are working beautifully now. but not semibold / 600

**Comment by markconroy** [comment]
Damn it. I guess semi bold needs to be numeric. So we probably have 2 options:

1. We change the form values to use numbers for their keys `400|Normal, 600|Semi bold, 700|Bold`
2. We add an `if` statement to set the value to `600` if semi-bold is chosen. 

Any preference?

**Comment by finnlewis** [comment]
@msayoung could you comment as to any preference?

**Comment by markconroy** [comment]
I think my preference would be the first option - `400|Normal, 600|Semi-bold` - _just in case_ in the future we decide to add in any more weights, it means we won't have to go back to write a second or third clause in our PHP.

**Comment by msayoung** [comment]
makes sense @markconroy

**Comment by markconroy** [comment]
Ok, let's merge this so as we'll need to quotes removed for that approach to work, so this PR is correct. And we'll create a follow up issue for the field config to change to numbers.

**Pull request merged**
