### PR TITLE
Extends from base events template instead of overriding

### LINKED ISSUE #278: Update event template to 'extend' from localgov_base and use twig block for breadcrumb
Follow-up to https://github.com/localgovdrupal/localgov_microsites_base/pull/276

```
{% block breadcrumbs %}
  <add-breadcrumbs-code>
{% endif %}

{% extends '@localgov_base/.../node--event--full.html.twig`
```

### PR DESCRIPTION
**Pull request by markconroy**
Closes #278 

## What does this change?

Uses Twig extend to inherit from `localgov_base` and just inject the breadcrumbs where needed instead of overriding the whole file and not being able to benefit from updates the base file receives.

## How to test

Check that everything works as it currently does - basically that event nodes still have breadcrumbs.

---
Thanks to [Big Blue Door](https://www.bigbluedoor.net/) for sponsoring my time to work on this.

### CODE REVIEW

**Comment by finnlewis** [comment]
I'll test it!

**Comment by stephen-cox** [comment]
@finnlewis or @stephen-cox to hopefully test this!

**Review by stephen-cox — APPROVED** [review]
Looks fine to me. Only think to note is the breadcrumb block was added to events with Base 1.7.0, so might be worth updating the requires version in composer: https://github.com/localgovdrupal/localgov_microsites_base/blob/8bf2199ba94b2bd719497ea3469e9b580a29f2ef/composer.json#L9

**Comment by markconroy** [comment]
@stephen-cox I think we'll need to update this PR slightly after Maria noticed we have no node title in events - #285 

That's fixed now, but we'll need to add the node title into that `{% block breadcrumb %}` section in this PR as well.

**Comment by markconroy** [comment]
@stephen-cox do you want to give this another quick test?

The difference between this one and the last one is that the node title should now also be printed in this template (since we don't use the page title block in microsites nodes).

Thanks.

**Review by stephen-cox — APPROVED** [review]
Works fine. I still suggest bumping the version of localgov_base this theme depends on to 1.7.0 in the `composer.json` file.

**Comment by finnlewis** [comment]
@markconroy could we check if this fails gracefully if using an older version of localgovdrupal/localgov_base?

If so, cool, if not, maybe we do want to set the minimum version to 1.7.0 as suggested?

**Comment by markconroy** [comment]
I agree with @stephen-cox, I think we'd be better to to set localgov_base 1.7.0 as our minimum since that's the release that introduces the twig block to allow this work to happen.

**Comment by markconroy** [comment]
Minimum version for `localgov_base` is now 1.7.0. 

Everyone okay if we commit this?

**Pull request merged**
